---
- name: Download tomcat
  shell: 'wget http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version|first() }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
    -O /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz creates=/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz'
  register: tomcat_downloaded

- name: Extract tomcat
  shell: 'tar xzf /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz -C /opt/'
  when: tomcat_downloaded|changed

- name: Create tomcat symlink
  file: path={{ alfresco_user_home }}/tomcat state=link src=/opt/apache-tomcat-{{ tomcat_version }}
  when: tomcat_downloaded|changed

- name: Set shared loader
  lineinfile: dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/catalina.properties regexp="^shared.loader=" line="shared.loader=${catalina.base}/shared/classes,${catalina.base}/shared/lib/*.jar"

- name: Set URIEncoding
  lineinfile: dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/server.xml insertafter="^\s{4}<Connector port=\"8080\"" line="               URIEncoding=\"UTF-8\""

- name: Set SSLAuthenticator
  lineinfile: dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/context.xml insertbefore="^</Context>" line="    <Valve className=\"org.apache.catalina.authenticator.SSLAuthenticator\" securePagesWithPragma=\"false\" />"
